"""Report generation actions.

Handles the final writing step: context assembly → prompt selection → LLM call.
"""

import logging

from researcher.config import Config
from researcher.llm_providers import get_llm_provider
from researcher.prompts import (
    get_report_by_type,
    get_short_conclusion_prompt,
    get_summarize_prompt,
)

logger = logging.getLogger(__name__)

# Minimum character count for a scraped source to be worth summarising.
_MIN_CONTENT_LENGTH = 100


def _assemble_context(context: list[dict]) -> str:
    """Format a list of scraped-source dicts into a single attributed string.

    Each source block looks like::

        Source: https://example.com
        ─────────────────────────────
        … cleaned page text …


    Args:
        context: List of dicts with at minimum ``"url"`` and ``"raw_content"``.

    Returns:
        Single string ready to be inserted into an LLM prompt.
    """
    parts: list[str] = []
    for item in context:
        url = item.get("url", "unknown source")
        content = item.get("raw_content", "").strip()
        if content:
            parts.append(f"Source: {url}\n{'─' * 60}\n{content}")
    return "\n\n".join(parts)


async def write_report(
    query: str,
    context: list[dict],
    cfg: Config,
    report_type: str = "research_report",
    agent_role_prompt: str = "",
    websocket=None,
    cost_callback: callable = None,
    custom_prompt: str = "",
) -> str:
    """Write a full research report using the gathered context.

    Assembles all scraped sources into a single attributed context string,
    selects the right prompt template (or uses a caller-supplied custom prompt),
    and calls SMART_LLM to write the report.

    Args:
        query:             The research question.
        context:           List of scraped-source dicts
                           ``[{"url": str, "raw_content": str, ...}, ...]``.
        cfg:               Researcher configuration.
        report_type:       One of ``"research_report"``, ``"outline_report"``,
                           ``"resource_report"``.  Ignored when *custom_prompt*
                           is provided.
        agent_role_prompt: System message that sets the researcher persona.
        websocket:         Reserved for future streaming output.
        cost_callback:     Optional callable for token-cost accounting.
        custom_prompt:     If non-empty, used verbatim instead of the standard
                           prompt template.  The assembled context is appended
                           as ``"\\n\\nContext: <context>"``.

    Returns:
        The completed Markdown report string, or ``""`` if the LLM call fails.
    """
    assembled_context = _assemble_context(context)

    if custom_prompt:
        user_content = f"{custom_prompt}\n\nContext:\n{assembled_context}"
    else:
        prompt_fn = get_report_by_type(report_type)
        user_content = prompt_fn(
            question=query,
            context=assembled_context,
            report_source=cfg.REPORT_SOURCE,
            report_format=cfg.REPORT_FORMAT,
            total_words=cfg.TOTAL_WORDS,
            language=cfg.LANGUAGE,
        )

    messages = [
        {"role": "system", "content": agent_role_prompt or "You are an expert research analyst."},
        {"role": "user", "content": user_content},
    ]

    try:
        provider = get_llm_provider(cfg.SMART_LLM, cfg.TEMPERATURE, cfg.SMART_TOKEN_LIMIT)
        report = await provider.get_chat_response(messages, max_tokens=cfg.SMART_TOKEN_LIMIT)
        if cost_callback:
            # OPUS FIX (3I): forward real token counts.
            cost_callback({"llm": cfg.SMART_LLM, **provider.last_usage})
        return report
    except Exception as exc:
        logger.error("write_report failed: %s", exc)
        return ""


async def write_report_conclusion(
    query: str,
    report_body: str,
    cfg: Config,
    cost_callback: callable = None,
) -> str:
    """Generate a 2–3 paragraph conclusion for an existing report body.

    Uses FAST_LLM (cheap and fast) because conclusions are short and do not
    require the same quality level as the full report.

    Args:
        query:       The research question the report answers.
        report_body: The full report text generated by :func:`write_report`.
        cfg:         Researcher configuration.
        cost_callback: Optional token-cost callback.

    Returns:
        A conclusion section string (plain Markdown), or ``""`` on failure.
    """
    # OPUS FIX (3B): use the centralised prompt template instead of an inline string.
    prompt = get_short_conclusion_prompt(query=query, report_body=report_body)
    messages = [{"role": "user", "content": prompt}]

    try:
        provider = get_llm_provider(cfg.FAST_LLM, cfg.TEMPERATURE, cfg.SUMMARY_TOKEN_LIMIT)
        conclusion = await provider.get_chat_response(messages, max_tokens=cfg.SUMMARY_TOKEN_LIMIT)
        if cost_callback:
            # OPUS FIX (3I): forward real token counts.
            cost_callback({"llm": cfg.FAST_LLM, **provider.last_usage})
        return conclusion
    except Exception as exc:
        logger.error("write_report_conclusion failed: %s", exc)
        return ""


async def summarize_url(
    url: str,
    content: str,
    query: str,
    cfg: Config,
    cost_callback: callable = None,
) -> str:
    """Compress a single scraped source down to query-relevant information.

    Called once per URL during the context-compression phase.  Uses FAST_LLM
    so that many sources can be summarised cheaply in parallel.

    Args:
        url:     The source URL (included in the summary for attribution).
        content: Raw page text from the scraper.
        query:   The research question; determines relevance.
        cfg:     Researcher configuration.
        cost_callback: Optional token-cost callback.

    Returns:
        A short query-relevant summary string.  Returns ``""`` immediately if
        content is empty or shorter than ``_MIN_CONTENT_LENGTH`` characters
        (avoids burning tokens on stubs / error pages).

        Also returns ``""`` if the LLM responds with the sentinel
        ``"IRRELEVANT"`` (see :func:`~researcher.prompts.get_summarize_prompt`).
    """
    if not content or len(content) < _MIN_CONTENT_LENGTH:
        logger.debug("Skipping summarise for %s — content too short (%d chars)", url, len(content))
        return ""

    prompt = get_summarize_prompt(query=query, raw_data=content)
    messages = [{"role": "user", "content": prompt}]

    try:
        provider = get_llm_provider(cfg.FAST_LLM, cfg.TEMPERATURE, cfg.SUMMARY_TOKEN_LIMIT)
        summary = await provider.get_chat_response(messages, max_tokens=cfg.SUMMARY_TOKEN_LIMIT)
        if cost_callback:
            # OPUS FIX (3I): forward real token counts.
            cost_callback({"llm": cfg.FAST_LLM, **provider.last_usage})
    except Exception as exc:
        logger.error("summarize_url failed for %s: %s", url, exc)
        return ""

    if not summary or summary.strip().upper() == "IRRELEVANT":
        logger.debug("Source %s marked IRRELEVANT for query %r", url, query)
        return ""

    return f"Source: {url}\n{summary.strip()}"
